apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-app-svc-mon
  labels:
    app: server-app-svc-mon
    release: prometheus
spec:
  selector:
    matchLabels:
      app: server-app-svc
  endpoints:
    - port: web